version: 2
services:
  - type: web
    name: muscify-backend
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000

  - type: web
    name: muscify-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: muscify-backend
          type: web
          property: host
